### ISSUE TITLE
Casting nested models without HasOne or HasMany

### ISSUE THREAD

**Issue by muratcorlu** [ddramone/json2tsmodel#5]
I think it should be possible to manage nested models with just `@Cast()` decorator, like:

```ts
class Option extends BaseModel {
  @Cast() id: string;
  @Cast() name: string;
}

class Question extends BaseModel {
  @Cast() question: string;
  @Cast() options: Option[];
}
```

It would be very helpful to have this.

**Comment by ddramone** [comment]
Generally i like the idea and i also have it in my mind, And yes, it is possible by reading `design:type` metadata using `ReflectMetadata`.

But there are few problems with this approach:

if you have following props: 

## Problem 1:
```
@Cast() id: number,
@Cast() question: Question,
```
you would expect that `question` is casted to the new instance of `Question` object based on it's own property definitions. But if `@Cast` decorators becomes responsible of reading types, it should also ensure that `id` is always a `number` and not a `string`. Currently `@Cast` decorator has no responsibility like this.

This is also totally fine, it will read `number` type from `id` and will ensure that it's always a number despite what comes out from your `json`. 


But, in this case you should always have `number` type even if you have default value:

```
@Cast() id = 5; // < This will not work
@Cast() id: number = 5; // You'll always need to specify type.
```

And it's against most of the linter rules. For primitive types you shouldn't put type definition if you're assigning value to it.


## Problem 2:

This will not work for the replacement of `@HasMany` decorator, since it's not yet supported in typescript. Basically problem is that it will give `Array` as a type from following:

`@Cast() question: Question[]`

i.e. it's gonna be a bit vague to have ditch `@HasOne` decorator (since it's possible today) but to ditch `@HasMany`.

That's why i'm subscribed to `https://github.com/Microsoft/TypeScript/issues/7169` and if there will be any update, i'm gonna make major changes.
